// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Snapshot.Pro
{
    internal sealed partial class Vsix
    {
        public const string Id = "Snapshot.Pro.51a382c6-eec9-4059-b517-e9d158d3781b";
        public const string Name = "Snapshot.Pro";
        public const string Description = @"The package provides you with a command to save a snapshot of the entire window.Snapshot.Pro";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Denis535";
        public const string Tags = "";
    }
}
